// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wommjvomwvxfdcbfbolj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvbW1qdm9td3Z4ZmRjYmZib2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTExNjMsImV4cCI6MjA2MTY4NzE2M30.djf7Ym9nbd84ukzLV19FyETYGnzzeKbICS5UEZqoCY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);