
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvxsvgtqplxypukvjoqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2eHN2Z3RxcGx4eXB1a3Zqb3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODYwNTQsImV4cCI6MjA2MTY2MjA1NH0.FHU2wbFEcGMVKGrmFK32AXTSUSClYOLxJcfa8H2ZJEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
